---
engines:
  pylint:
    enabled: true
    python_version: 3

exclude_paths:
  - **.json

duplication:
  enabled: true
  exclude_paths:
    - scripts/tests/test_consolidate_treatment_arm_collections.py

