version: "3"
services:
  treatment-arm-api:
    build: .
    command: python app.py
    image: "fnlcr/nci-adult-match-treatment-arm-api"
    ports:
      - "5010:5010"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/Match
      - ENVIRONMENT=development
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_DATABASE=${AUTH0_DATABASE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_USERNAME=${AUTH0_USERNAME}
      - AUTH0_PASSWORD=${AUTH0_PASSWORD}
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    volumes:
      - ./scripts:/scripts
#  treatment-arm-message-manager:
#    image: "fnlcr/nci-adult-match-treatment-arm-api"
#    command: python scripts/ta_message_manager/ta_message_manager.py
#    depends_on:
#      - mongo
#    environment:
#      - MONGODB_URI=mongodb://mongo:27017/Match
#      - ENVIRONMENT=development
#      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
#      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
#      # this SHOULDN'T be necessary, but dockerized python can't find modules for script in a directory without it
#      - PYTHONPATH=.
  patient-api:
    image: "fnlcr/nci-adult-match-patient-api"
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/Match
      - ENVIRONMENT=development
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_DATABASE=${AUTH0_DATABASE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
    # volumes: # this config is to override the default Patient API assay rules config. Normally commented out.
    #   - ./misc/config/nci-adult-match-patient-api-assay_activation_rules.json:/usr/app/config/assay_activation_rules.json
#    networks:
#      - adult-match-net

  mongo:
    image: mongo:3.4.0
    volumes:
      - ./data_setup/match:/backup
    ports:
      - "27018:27017"

networks:
  adult-match-net:
    driver: bridge
