version: "3"
services:
  treatment-arm-api:
    build: .
    command: python app.py
    image: "fnlcr/nci-adult-match-treatment-arm-api"
    ports:
      - "5010:5010"
    depends_on:
      - mongo
    environment:
      - UNITTEST=1  # disables auth0 authentication in the local environment
      - MONGODB_URI=mongodb://mongo:27017/Match
      - ENVIRONMENT=development
      - SQS_QUEUE_NAME=treatment-arm-api-dev-smithmak-queue
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_DATABASE=${AUTH0_DATABASE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_USERNAME=${AUTH0_USERNAME}
      - AUTH0_PASSWORD=${AUTH0_PASSWORD}
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    volumes:
      - ./scripts:/scripts
      - ./config:/config
      - ./helpers:/helpers
  patient-api:
    image: "fnlcr/nci-adult-match-patient-api"
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - UNITTEST=1  # disables auth0 authentication in the local environment
      - MONGODB_URI=mongodb://mongo:27017/Match
      - ENVIRONMENT=development
      - LOGGER_LEVEL=INFO
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_DATABASE=${AUTH0_DATABASE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_MANAGEMENT_ID=${AUTH0_MANAGEMENT_ID}
      - AUTH0_MANAGEMENT_SECRET=${AUTH0_MANAGEMENT_SECRET}
    # volumes: # this config is to override the default Patient API assay rules config. Normally commented out.
    #   - ./misc/config/nci-adult-match-patient-api-assay_activation_rules.json:/usr/app/config/assay_activation_rules.json

  mongo:
    image: fnlcr/nci-adult-match-datastore:latest
    volumes:
      - ./data_setup/match:/backup
    ports:
      - "27018:27017"
