version: "3"
services:
  treatment-arm-api:
    build: .
    command: python app.py
    image: "fnlcr/nci-adult-match-treatment-arm-api"
    ports:
      - "5010:5010"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/Match
      - ENVIRONMENT=development
  mongo:
    image: mongo:3.4.0
    volumes:
      - ./data_setup/match:/backup
    ports:
      - "27018:27017"
