development:
  port: 5010
  visibility_timeout: '36000'
  region: "us-east-1"
  bucket: "adultmatch-dev"
  tmp_file_dir: "/tmp"
  polling_interval: 10
  read_capacity: 5
  write_capacity: 5
  aws_download_time_limit: 600
  aws_upload_time_limit: 3600
  patient_api_url: "http://patient-api:5000/api/v1/patients"
#  patient_api_url: "http://localhost:5000/api/v1/patients"

test:
  port: 5010
  visibility_timeout: '36000'
  region: "us-east-1"
  bucket: "adultmatch-int"
  tmp_file_dir: "/tmp"
  polling_interval: 10
  read_capacity: 5
  write_capacity: 5
  aws_download_time_limit: 600
  aws_upload_time_limit: 3600
  patient_api_url: "https://match-int.nci.nih.gov/api/v1/patients"

uat:
  port: 5010
  visibility_timeout: '36000'
  region: "us-east-1"
  bucket: "adultmatch-dev"
  tmp_file_dir: "/tmp"
  polling_interval: 10
  read_capacity: 5
  write_capacity: 5
  aws_download_time_limit: 600
  aws_upload_time_limit: 3600
  patient_api_url: "https://match-uat.nci.nih.gov/api/v1/patients"

production:
  port: 5010
  visibility_timeout: '36000'
  region: "us-east-1"
  bucket: "adultmatch-dev"
  tmp_file_dir: "/tmp"
  polling_interval: 10
  read_capacity: 5
  write_capacity: 5
  aws_download_time_limit: 600
  aws_upload_time_limit: 3600
  patient_api_url: "[TBD]"
