development:
  port: 5010
  region: "us-east-1"
  bucket: "adultmatch-dev"
  tmp_file_dir: "/tmp"
  polling_interval: 5
  sqs_queue_name: 'treatment-arm-api-uidev-queue'
  patient_api_url: "http://patient-api:5000/api/v1/patients"
  logger_level: "DEBUG"

test:
  port: 5010
  region: "us-east-1"
  bucket: "adultmatch-int"
  tmp_file_dir: "/tmp"
  polling_interval: 10
  sqs_queue_name: 'treatment-arm-api-int-queue'
  patient_api_url: "https://match-int.nci.nih.gov/api/v1/patients"
  logger_level: "WARN"

uat:
  port: 5010
  region: "us-east-1"
  bucket: "adultmatch-uat"
  tmp_file_dir: "/tmp"
  polling_interval: 1
  sqs_queue_name: 'treatment-arm-api-uat-queue'
  patient_api_url: "https://match-uat.nci.nih.gov/api/v1/patients"
  logger_level: "INFO"

production:
  port: 5010
  region: "us-east-1"
  bucket: "adultmatch"
  tmp_file_dir: "/tmp"
  polling_interval: 1
  sqs_queue_name: 'treatment-arm-api-queue'
  patient_api_url: "https://match.nci.nih.gov/api/v1/patients"
  logger_level: "WARN"
